#!/bin/sh

echo ""
echo ""
echo "================="
echo "available aliases"
echo "================="
echo ""
echo "aliashelp       : prints a list of the available aliases"
echo "aliassetup      : opens the .bash_profile in TextWrangler"
echo "cdhtdocs        : changes the current directory to the htdocs"
echo "clearsvn        : removes the .svn directories in the current directories recursively"
echo "hidehiddenfiles : hides the hidden files in Finder | killfinder must follow"
echo "hosts           : opens the list of the hosts in this machine"
echo "httpdconf       : opens the httpd.conf in TextWrangler"
echo "killfinder      : quits the Finder"
echo "phpini          : opens the php.ini in TextWrangler"
echo "showhiddenfiles : shows the hidden files in Finder | killfinder must follow"
echo ""
echo "==================="
echo "available functions"
echo "==================="
echo ""
echo "openproject [PARAM] : opens the [PARAM] project in Finder"
echo "permissions [PERMISSIONS] [PATH_TO_FOLDER] : chmod -R -v -v [PERMISSIONS] [PATH_TO_FOLDER]"
echo ""
echo ""